zook/zook.go
=> detect master to use by lowest node id

README.md, eremetic.yml.example, handler/driver.go, handler/scheduler.go, handler/scheduler_test.go, handler/task.go, handler/task_test.go, types/request.go
also noticed that if you call get right after post you get a 404. Guess we should return "waiting" or whatever as status at that point
=> More data more better

handler/handler.go, handler/handler_test.go, handler/scheduler.go, handler/scheduler_test.go, handler/task.go, handler/task_test.go, types/request.go
please review @alde 
I moved lots of code around
=> move creation of task structure to request handler

Makefile, README.md, docker/Dockerfile, docker/marathon.sh, handler/scheduler_test.go, misc/eremetic.json
cleaned up my dockerfile from klarnasque stuff.
=> adding docker file

eremetic.go, handler/handler.go, handler/handler_test.go, routes/routes.go, routes/routes_test.go, scheduler/driver.go, scheduler/driver_test.go, scheduler/main.go, scheduler/scheduler.go, scheduler/scheduler_test.go, scheduler/task.go, scheduler/task_test.go, types/scheduler.go
Introduces a new Scheduler interface that holds ScheduleTask
=> extract the scheduler from handler package

database/database_test.go, database/task.go, formatter/formatter.go, formatter/formatter_test.go, handler/handler.go, handler/handler_test.go, scheduler/scheduler.go, scheduler/scheduler_test.go, scheduler/task.go, scheduler/task_test.go, static/css/style.css, templates/error_404.html, templates/task.html, types/task.go
The Status struct contains a Time and a Status element, so that a history of
status changes can be viewed.
Solves #13
=> Change Status to a slice containing Status structs

.gitignore, Makefile, docker/Dockerfile, generate.go, handler/handler.go, routes/routes.go
Add go generate to Makefile
Stop copying assets and templates to docker folder
=> Use bindata-assetfs to bundle assets and templates

.travis.yml, Makefile
automagic publish to docker hub. You will need to set some secret environment variables as per http://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry
=> Publish docker

scheduler/scheduler.go, scheduler/scheduler_test.go, scheduler/task.go, scheduler/task_test.go
=> Don't modify the input when creating mesos task

.travis.yml, Makefile, misc/docker.sh
* Builds docker image when running on tags in addition to on master
* Alias images built from tags as :latest
=> Publish tagged version to docker

README.md, handler/handler.go, scheduler/scheduler.go, scheduler/task.go, types/request.go, types/task.go
When IsTerminal is reached, notify a callback by sending the
final State with a HTTP POST.
Fixes #47
=> Notify callback

database/database_test.go, handler/handler.go, handler/handler_test.go, scheduler/scheduler_test.go, scheduler/task.go, scheduler/task_test.go, types/task.go
This makes what you GET look a bit more like what you POST
=> Remove protobuf members from task struct

README.md, scheduler/task.go, scheduler/task_test.go, types/request.go, types/task.go
The extract flag is set based on the same list of suffixes as used by
marathon
=> Support adding uris to command info

misc/swagger.yaml
=> Add swagger describing the api

handler/handler.go, handler/handler_test.go
This is a temporary solution until we implement a JSON-schema validation
=> Improve the Error message from POSTing a json

.gitignore, README.md, eremetic.go, eremetic.yml.example, eremetic_test.go, handler/handler.go, routes/routes.go, scheduler/main.go, scheduler/match.go, scheduler/reconcile.go, scheduler/scheduler.go, scheduler/scheduler_test.go
Add support for JSON log format
Fixes #57
=> Switch to logrus

handler/handler.go, scheduler/callback.go, scheduler/scheduler.go, scheduler/scheduler_test.go
=> Error on full queue

scheduler/task.go, scheduler/task_test.go, types/task.go
If no command is specified in the JSON payload, or if it's an empty
string, default to running the default command of the docker image.
Fixes #55
=> Run default docker command

database/task.go, handler/handler.go, misc/swagger.yaml, routes/routes.go
This provides additional visibility to the user as to what is going on. While I see an eventual UI element being added to this, adding JSON-only for now to get the ball rolling.
=> add route to list all running tasks

eremetic.go, eremetic_test.go, scheduler/driver.go, scheduler/driver_test.go, scheduler/main.go, scheduler/scheduler.go, scheduler/scheduler_test.go
Expanded on the settings struct. Got a big block of viper.gets but I think thats ok
=> Wipe out viper from scheduler module

README.md, scheduler/task.go, scheduler/task_test.go, types/request.go, types/task.go
Introduce `force_pull_image` for set forcePullImage flag.
=> Add ability to force docker to pull image before launching each task

config/config.go, eremetic.go, handler/handler.go, handler/handler_test.go, handler/helpers.go, routes/routes.go, routes/routes_test.go, scheduler/scheduler.go, scheduler/scheduler_test.go, templates/index.html, templates/task.html, version.go
Add API-endpoint `/version`
Add version to GUI
fixes #103
=> Expose eremetic version

types/task.go, types/task_test.go
while adding a unit test for ForcePullImage, I noticed my patch didn't apply correctly and I pushed dead code. So here's the fix (and the unit test). Sorry for the inconvenience.
=> fix ForcePullImage and add unit test

database/boltdb_test.go, database/zookeeper_test.go, handler/handler_test.go, scheduler/callback.go, scheduler/reconcile_test.go, scheduler/scheduler.go, scheduler/scheduler_test.go, scheduler/task_test.go, types/states.go, types/task.go, types/task_test.go, types/types_test.go
Shuffling code around to allow for custom task state. still need to actually and the queue state.
Fixes #110
=> Add task queued state

Makefile, handler/handler.go, handler/handler_test.go, handler/helpers.go, handler/helpers_test.go, mocks/mocks.go, routes/routes.go, routes/routes_test.go
Add some missing tests
Fixes #45
Revert -trace in tests
=> Unify the building of routes

Makefile, config/config.go, config/config_test.go, eremetic.go, eremetic_test.go, handler/handler.go, handler/handler_test.go, handler/helpers.go, handler/helpers_test.go, version/version.go
Cutting some other stuff from `Config`
=> Version is not configurable

boltdb/boltdb.go, misc/swagger.yaml, server/handler.go
=> List tasks empty db

README.md, client/client.go, client/client_test.go, cmd/hermit/README.md, cmd/hermit/main.go
Introduces a CLI client for querying the Eremetic server.
=> Add hermit cli

LICENSE, README.md
Also update some out of date information
=> Update readme with goreportcard

mesos/task.go, mesos/task_test.go
=> Add port mapping when allocating unspecified port

cmd/hermit/main.go
Simple PR to add uris and args support via hermit client.
This means that we can launch a eremetic task through hermit without and command args. Thats why I have removed the condition :
```
if len(args) == 0 {		
cmd.flags.Usage()		
os.Exit(1)		
}
```
Now we can several uris and args through the hermit, although it was already possible through API.
=> Add args and uris in the hermit client

docker/Dockerfile
Upgrade of alpine image could fix issue #169
=> upgrade version of base alpine image

cmd/eremetic/eremetic.go, mesos/scheduler.go, metrics/metrics.go
Reasoning being this is not mesos api construct but rather eremetic
specific concepts.
Ref #172, Breaking out some changes
=> Move metric definitions to new package

mesos/match.go, mesos/match_test.go, mesos/reconcile.go, mesos/scheduler.go, mesos/task.go, mesos/task_test.go, server/helpers.go, server/templates/index.html, server/templates/task.html, task.go
This changes type names, field names, and log fields. API still uses the
old naming.
=> Internal rename of slave -> agent

cmd/eremetic/eremetic.go, mesos/driver.go, mesos/driver_test.go, mesos/scheduler.go, mesos/scheduler_test.go
More adaptations from #172 to reduce noise from non api changes
=> Scheduler driver restructure

README.md, api/api_test.go, api/api_v0.go, api/api_v1.go, mesos/task.go, mesos/task_test.go, misc/eremetic.json, misc/swagger.yaml, task.go, task_test.go
=> Add a 'privileged' flag to allow running privileged containers in eremetic.

mesos/scheduler.go, mesos/scheduler_test.go
Some changes to logging to possibly help understand #187
=> Check launch tasks

docker/Dockerfile
=> added ca-certificates in Dockerfile
