eremetic.go

this lets us do stuff like
```ZOOKEEPER=foobar ./eremetic```

enable automatic configuration from environment

---

handler/handler.go

This is needed when e.g runnig the framework as a docker container as
the port has to be explicitly mapped when starting the container and the
published ip needs to be that of the host

make mesos port and published address configurable

---

handler/task.go
handler/task_test.go

The generated task id is exported as `MESOS_TASK_ID` just like marathon
does it.
https://mesosphere.github.io/marathon/docs/task-environment-vars.html

Add task id as environment variable

---

Makefile
eremetic.go
version.go

Update makefile to set current version based on information in git. If
the current commit has a signed tag "v1.2.3" the current version will be
set to "1.2.3". If there is no tag for the current a version string
based on the latest tag as per `git describe` will be used.
Also sets a build date for good measure

automatic version based on git tag

---

handler/handler.go

Nothing is ever put on the requests channel and after removing the
select loop over the channel the extra go routine can be eliminated

remove some dead code

---

.gitignore
database/database.go
database/database_test.go
database/task.go
eremetic.go
eremetic.yml.example
handler/handler.go
handler/handler_test.go
handler/scheduler.go
handler/scheduler_test.go
handler/task.go
handler/task_test.go
types/task.go

Instead of having tasks in memory, store them in a Key/Value database.
Database will by default be created in db/eremetic.db relative to the
executable if nothing else is configured.
Removes the 1 hour time limit on reading requests.
Refactored EremeticTask into types package.
solves #12

Implement support for BoltDB database backing

---

scheduler/match.go
scheduler/match_test.go
scheduler/scheduler.go

This should stop eremetic from trying to launch tasks on offers without enough resources.
Future improvements are to perhaps give up on a task if we can't launch it after X minutes. Also right now it freaks out and rejects all offers when a task can't be launched

Filter offers

---

docker/marathon.sh

A small fix for the issue I hit - #36. 
Still no idea why `nslookup` inside container returns two adresses in one line, but this fix works for me.

Fix messenger address in container

---

scheduler/metrics.go
scheduler/scheduler.go
types/task.go
types/task_test.go

When doing reconciliation after a restart the difference between
launched_tasks and terminated_tasks is not guaranteed to yield the
currently running tasks. This new gauge will account for running tasks
that were recovered.

Extend metrics with a running tasks gauge

---

README.md
database/database_test.go
database/task.go
handler/handler_test.go
misc/swagger.yaml
scheduler/scheduler.go
scheduler/task.go
scheduler/task_test.go
types/request.go
types/task.go

The purpose of these is to be able to pass in for example credentials to
your docker container at runtime, but not have them exposed through a
GET with the Eremetic API.
They are not encrypted, and will still be viewable if someone has access
to the machine running the task, as they are merged to the env field
before being passed to Mesos.
See the readme for more information, and follow best practices for
secure communication for REST-ful APIs.

Add support for Masked Environment variables

---

eremetic.go
scheduler/main.go
scheduler/scheduler.go

To provide a somewhat graceful shutdown the http server is wrapped by
manners and the ctrl+c handler is changed to close the framework driver.

Exit eremetic when framework driver closes

---

README.md
database/boltdb.go
database/boltdb_test.go
database/database.go
eremetic.go
eremetic_test.go
handler/handler.go
handler/handler_test.go
routes/routes.go
routes/routes_test.go
scheduler/reconcile.go
scheduler/reconcile_test.go
scheduler/scheduler.go
scheduler/scheduler_test.go

In order to prepare for adding support for more different databases, an
abstraction for the database drivers is needed.

Create a database abstraction

---

handler/handler.go
handler/handler_test.go
handler/helpers.go
routes/routes.go
scheduler/extractor.go
scheduler/extractor_test.go
scheduler/scheduler.go
scheduler/task.go
static/css/style.css
static/js/ansi_up.js
static/js/task_view.js
templates/task.html
types/task.go

Add /stdout and /stderr endpoints on a task resource to access logs from the sandbox

Provide access to sandbox logs

---

Makefile
README.md
examples.md
handler/helpers.go
scheduler/match.go
scheduler/match_test.go
scheduler/scheduler.go
static/css/style.css
static/js/eremetic.js
templates/index.html
templates/task.html
types/request.go
types/task.go

Fixes #78 
Rebase and squash of #88

Task attribute constraints

---

scheduler/task.go
scheduler/task_test.go
types/task.go
types/task_test.go

Move merging of uris/fetch from launch task to create tasks by
replacing URIs/Fetch element from EremeticTask to a single one, FetchURIs,
loosely based on mesos protobuf.
This change breaks the 1:1 mapping on request to task.

Refactor uris/fetch

---

database/boltdb.go
database/boltdb_test.go
database/zookeeper.go
database/zookeeper_test.go

go lint doesn't like it, but it's nicer for clients

Return empty array instead of `null` when tasks list is empty

---

scheduler/scheduler_test.go

The scheduler test is quite massive and personally I had some difficulty of keeping track of the state in each test case. Splitting the test (hopefully) makes it easier to follow.
Also, since Eremetic is using GoConvey for tests, which AFAIK made for BDD-style tests, I took the liberty of reformulating the test cases in the form of Given, When, Then.
The actual tests haven't been modified though. Let me know if you think that's the case or whether my test descriptions are accurate or not.

Extract scheduler tests into smaller ones

---

LICENSE
README.md
cmd/hermit/main.go

Adds some filtering options to the ls subcommand:
`hermit ls -filter "min_age=5m,status=running"` lists all tasks that have been running for longer than 5 minutes

hermit: Allow filtering output

---

README.md
cmd/hermit/main.go
mesos/task.go
mesos/task_test.go

Adds the assigned host ports to the environment to allow tasks to announce where to find them.

Add host ports to task environment

---

Makefile
boltdb/boltdb.go
boltdb/boltdb_test.go
callback.go
callback_test.go
client/client.go
cmd/eremetic/eremetic.go
cmd/hermit/main.go
database.go
mesos/extractor.go
mesos/extractor_test.go
mesos/match.go
mesos/match_test.go
mesos/reconcile.go
mesos/reconcile_test.go
mesos/scheduler.go
mesos/scheduler_test.go
mesos/task.go
mesos/task_test.go
mock/mock.go
scheduler.go
server/handler.go
server/handler_test.go
server/helpers.go
server/helpers_test.go
task.go
task_test.go
zk/zookeeper.go
zk/zookeeper_test.go

This PR fixes the issues from running `golint` on eremetic. Unnecessarily exported symbols have been unexported and basic documentation has been added for the exported APIs.
Added basic linting and vetting targets to the Makefile.

Fix linter errors

---

client/client.go
client/client_test.go
cmd/hermit/main.go
mesos/reconcile_test.go
mesos/scheduler.go
mesos/scheduler_test.go
mock/mesos_scheduler.go
mock/mock.go
scheduler.go
server/handler.go
server/helpers.go
server/routes.go
server/routes_test.go
server/static/css/style.css
server/static/js/task_view.js
server/templates/task.html
task.go

Add possibility to kill tasks
Use either the REST API or hermit to kill a task you no longer wish to
run.
POST /task/{taskID}/kill
hermit kill {taskID}
Add button in GUI for killing tasks

Add killswitch for tasks

---

boltdb/boltdb.go
boltdb/boltdb_test.go
database.go
mock/mock.go
server/handler.go
server/handler_test.go
server/routes.go
server/routes_test.go
zk/zookeeper.go
zk/zookeeper_test.go

This PR adds a simple delete through API REST.
It's useful for cases where the framework has tasks in the queue, but Mesos cannot provide appropriate resources to the framework.

Implemented delete task and added test for zk and bolt

---

cmd/hermit/main.go

This is to be able to add simple integration of environment variables that later we pass to docker, through hermit.
Its already avaliable in API of eremetic. With this PR it just enables docker look alike flags
`hermit run -image=busybox -e MYVAR=value1 -e MYVAR2=value2`

Add support for environment variables in hermit

---

README.md
cmd/hermit/main.go
mesos/task.go
mesos/task_test.go
misc/swagger.yaml
task.go
task_test.go

-support for the network mode host
-pass the dns parameter to the docker
As we discussed earlier I have added the flag for the dns to avoid opening the parameters in the Eremetic API.

Add support for network host mode and pass dns to the docker

---

mesos/match.go
mesos/match_test.go
mesos/scheduler_test.go

As mentioned in #163 the basic support to reject offers if the node is currently in maintenance window.

Basic support for maintenance mode of mesos

---

mesos/builders.go
mesos/match_test.go
mesos/task_test.go

Adds small functions to help bulid test data the idea being that less stuff needs to change in the tests for #172

Test data builders

---

.gitignore
Makefile
README.md
api/api_test.go
api/api_v0.go
api/api_v1.go
api/route.go
api/version.go
client/client.go
client/client_test.go
cmd/hermit/main.go
database.go
misc/swagger.yaml
server/handler.go
server/handler_v1_test.go
server/helpers.go
server/routes.go
server/routes_test.go
server/routes_v0.go
server/routes_v1.go
server/static/css/style.css
server/static/js/eremetic.js
server/static/js/task_view.js
server/templates/index.html
server/templates/task.html
task.go
version/version.go

All existing endpoints available under both `/api/v1/task/` and the old `/tasks` endpoint.
Use agent_* for requests and responses to new routes instead of slave_*
Only JSON responses
Add Warning header with Deprecation information to old routes
Should API change more while we're at it?

Add /api/v1/ routes

---

README.md
api/api_test.go
api/api_v0.go
api/api_v1.go
mesos/scheduler_test.go
mesos/task.go
mesos/task_test.go
misc/swagger.yaml
server/static/css/style.css
server/static/js/eremetic.js
server/templates/index.html
task.go
task_test.go

Implementation of #56
This is a use case that is gonna help us propagating the labels to the Mesos cluster. 
In our case, it's for reporting the Mesos cluster usage, by different frameworks. And I can think that could help others also.

Add support for labels

---

boltdb/boltdb.go
boltdb/boltdb_test.go
database.go
glide.lock
glide.yaml
mesos/reconcile.go
mesos/scheduler.go
misc/swagger.yaml
mock/mock.go
server/handler.go
server/handler_test.go
server/routes_v0.go
server/routes_v1.go
server/server_test.go
task.go
task_test.go
zk/zookeeper.go
zk/zookeeper_test.go

Second part of #184
Basically this PR allows to filter tasks using query params like `/api/v1/task?name=foo` or `/api/v1/task?state=terminated`
`state` query param can be composite states like `state=terminated,queued` or state=`active,queued` that is by default filter.
I have already added this to enable us for future extensions. So adding a new query param is basically adding a field to `TaskFilter` and changing the `Match` method.
Moreover passing the `TaskFilter` to `db` methods for any future query optimisation any db can do.

Add support to filter tasks by name and list terminated tasks

---

config/config.go
mesos/scheduler.go

Adding default frameworkID to scheduler config, adding automatic reconnect for framework/mesos disconnect. 
Tested in Rockerbox prod environment, behaves as expected (logs below):
`ERROR: logging before flag.Parse: I0201 21:08:12.343410       1 scheduler.go:419] New master master@<> detected
time="2022-02-01T21:08:12Z" level=debug msg="Framework disconnected with master, attempting to connect a new driver"
time="2022-02-01T21:08:12Z" level=debug msg="No credentials specified in configuration"
ERROR: logging before flag.Parse: I0201 21:08:12.344904       1 scheduler.go:334] Initializing mesos scheduler driver
ERROR: logging before flag.Parse: I0201 21:08:12.677563       1 scheduler.go:583] Framework registered with ID=1234`

Framework/mesos auto-reconnect
